CREATE DATABASE cromos;
USE cromos;

CREATE TABLE ALBUMES(
    ID     VARCHAR(90) NOT NULL,
    PRECIO NUMERIC     NOT NULL,
    ESTADO INT         NOT NULL,

    PRIMARY KEY (ID)

);


CREATE TABLE USUARIOS(
    NOMBRE      VARCHAR(70)  NOT NULL,
    APELLIDOS   VARCHAR(140) NOT NULL,
    EMAIL       VARCHAR(150) NOT NULL,
    ESADMIN     INT default 0, /*Por defecto null*/
    CONTRASENYA VARCHAR(140) NOT NULL,
    PUNTOS      NUMERIC      NOT NULL,

    PRIMARY KEY (EMAIL)
);

CREATE TABLE COLECCIONES(
    IDCOLUSER    INT          NOT NULL AUTO_INCREMENT,
    NOMBRE       VARCHAR(150) NOT NULL,
    IDALBUM      VARCHAR(150) NOT NULL,
    USUARIOEMAIL VARCHAR(150) NOT NULL,
    ESTADO       INT          NOT NULL,
    NUMCROMOS    VARCHAR(150) NOT NULL,

    PRIMARY KEY (IDCOLUSER),
    CONSTRAINT FK_IDALBUM FOREIGN KEY (IDALBUM) REFERENCES ALBUMES (ID),
    CONSTRAINT FK_EMAILUSUARIO FOREIGN KEY (USUARIOEMAIL) REFERENCES USUARIOS (EMAIL)

);

CREATE TABLE CROMOS
(
    ID      VARCHAR(90) NOT NULL,
    PRECIO  NUMERIC     NOT NULL,
    IMAGEN   VARCHAR(150) NOT NULL,
    NUMCOPIAS INT NOT NULL,
    IDALBUM VARCHAR(90) NOT NULL,

    PRIMARY KEY (ID),
    CONSTRAINT FK_NOMBREALBUM FOREIGN KEY (IDALBUM) REFERENCES ALBUMES (ID)

);

INSERT INTO USUARIOS(NOMBRE, APELLIDOS, EMAIL, ESADMIN, CONTRASENYA, PUNTOS)
VALUES ('PEPE', 'PANTANOS', 'pepepantanos@gmail.com', '1', 'pepe123', '0');
INSERT INTO ALBUMES(ID, PRECIO, ESTADO)
VALUES ('xy1', '12.27', '1');
INSERT INTO ALBUMES(ID, PRECIO, ESTADO)
VALUES ('sm1', '30.45', '1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-167','12','https://images.pokemontcg.io/sm1/167.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-129','24','https://images.pokemontcg.io/sm1/129.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-95','21','https://images.pokemontcg.io/sm1/95.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-101','15','https://images.pokemontcg.io/sm1/101.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-106','27','https://images.pokemontcg.io/sm1/106.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-64','30','https://images.pokemontcg.io/sm1/64.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-14','19','https://images.pokemontcg.io/sm1/14.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-92','20','https://images.pokemontcg.io/sm1/92.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-21','34','https://images.pokemontcg.io/sm1/21.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('sm1-69','29','https://images.pokemontcg.io/sm1/69.png','10','sm1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-125','12','https://images.pokemontcg.io/xy1/125.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-80','36','https://images.pokemontcg.io/xy1/80.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-35','21','https://images.pokemontcg.io/xy1/35.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-87','15','https://images.pokemontcg.io/xy1/87.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-126','23','https://images.pokemontcg.io/xy1/126.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-18','33','https://images.pokemontcg.io/xy1/18.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-55','19','https://images.pokemontcg.io/xy1/55.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-103','17','https://images.pokemontcg.io/xy1/103.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-124','14','https://images.pokemontcg.io/xy1/124.png','10','xy1');
INSERT INTO CROMOS(ID,PRECIO,IMAGEN,NUMCOPIAS,IDALBUM) VALUES ('xy1-69','19','https://images.pokemontcg.io/xy1/69.png','10','xy1');



