CREATE DATABASE cromos;
USE cromos;

CREATE TABLE ALBUMES(
    ID     VARCHAR(90) NOT NULL,
    PRECIO NUMERIC     NOT NULL,
    ESTADO INT         NOT NULL,

    PRIMARY KEY (ID)

);


CREATE TABLE USUARIOS(
    NOMBRE      VARCHAR(70)  NOT NULL,
    APELLIDOS   VARCHAR(140) NOT NULL,
    EMAIL       VARCHAR(150) NOT NULL,
    ESADMIN     INT default 0, /*Por defecto null*/
    CONTRASENYA VARCHAR(140) NOT NULL,
    PUNTOS      NUMERIC      NOT NULL,

    PRIMARY KEY (EMAIL)
);

CREATE TABLE COLECCIONES(
    IDCOLUSER    INT          NOT NULL AUTO_INCREMENT,
    NOMBRE       VARCHAR(150) NOT NULL,
    IDALBUM      VARCHAR(150) NOT NULL,
    USUARIOEMAIL VARCHAR(150) NOT NULL,
    ESTADO       INT          NOT NULL,
    NUMCROMOS    VARCHAR(150) NOT NULL,

    PRIMARY KEY (IDCOLUSER),
    CONSTRAINT FK_IDALBUM FOREIGN KEY (IDALBUM) REFERENCES ALBUMES (ID),
    CONSTRAINT FK_EMAILUSUARIO FOREIGN KEY (USUARIOEMAIL) REFERENCES USUARIOS (EMAIL)

);

CREATE TABLE CROMOS
(
    ID      VARCHAR(90) NOT NULL,
    PRECIO  NUMERIC     NOT NULL,
    IDALBUM VARCHAR(90) NOT NULL,

    PRIMARY KEY (ID),
    CONSTRAINT FK_NOMBREALBUM FOREIGN KEY (IDALBUM) REFERENCES ALBUMES (ID)

);

INSERT INTO USUARIOS(NOMBRE, APELLIDOS, EMAIL, ESADMIN, CONTRASENYA, PUNTOS)
VALUES ('PEPE', 'PANTANOS', 'pepepantanos@gmail.com', '1', 'pepe123', '0');
INSERT INTO ALBUMES(ID, PRECIO, ESTADO)
VALUES ('xy1', '12.27', '1');
INSERT INTO ALBUMES(ID, PRECIO, ESTADO)
VALUES ('sm1', '30.45', '1');



